apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service   # Name of service (we use this as domain in todo-app config)
spec:
  selector:
    app: grpc-server       # Exposes stream-web-app as service
  ports:
    - port: 5001
      targetPort: 80 # Map service port to container port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment     # Name of deployment, we wil refer this in service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: nishants/grpc-server:v0.1   # Image name for stream-web-app container
          ports:
            - containerPort: 80